#!/bin/sh
# Load nvm if available
[ -s "$HOME/.nvm/nvm.sh" ] && \. "$HOME/.nvm/nvm.sh"
# Add common Node.js paths
export PATH="$PATH:$HOME/.nvm/versions/node/$(nvm current)/bin:$HOME/.yarn/bin:/usr/local/bin"
npx --no-install commitlint --edit "$1"
